<?php

add_action('admin_init', 'rukhsar_custom_theme_options');

function rukhsar_custom_theme_options() {

    /* OptionTree is not loaded yet */
    if ( ! function_exists( 'ot_settings_id' ) )
        return false;

    /**
     * Get a copy of the saved settings array.
     */
    $saved_settings = get_option( ot_settings_id(), array() );

    /**
     * Custom settings array that will eventually be
     * passes to the OptionTree Settings API Class.
     */

    $custom_settings = array(
        'contextual_help' => array(
            'sidebar'       => ''
        ),
        'sections'        => array(
            array(
                'id'          => 'general',
                'title'       => esc_html__('General Setting', 'rukhsar' )
            ),
            array(
                'id'          => 'slider_sectio',
                'title'       => esc_html__('Slider Setting', 'rukhsar' )
            ),
            array(
                'id'          => 'sections_setting',
                'title'       => esc_html__('Sections Setting', 'rukhsar' )
            ),
            array(
                'id'          => 'footer_section',
                'title'       => esc_html__('Footer Setting', 'rukhsar' )
            ),

            array(
                'id'          => 'custom_layout_sec',
                'title'       => esc_html__('Homepage Custom Layout', 'rukhsar' )
            ),

        ),
        'settings'        => array(

            array(
                'id'          => 'style_tab',
                'label'       => esc_html__('Style Setting', 'rukhsar' ),
                'desc'        => '',
                'std'         => '',
                'type'        => 'tab',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'color_general',
                'label'       => esc_html__('Color Scheme', 'rukhsar' ),
                'desc'        => esc_html__('Pick your color scheme. Default color is black #000000', 'rukhsar' ),
                'std'         => '',
                'type'        => 'colorpicker',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'color_scheme',
                'label'       => esc_html__('Hyperlink Color', 'rukhsar' ),
                'desc'        => esc_html__('Pick your color for hyperlink. Default color is black #aaaaaa', 'rukhsar' ),
                'std'         => '',
                'type'        => 'colorpicker',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'custom_hovers',
                'label'       => esc_html__('Hyperlink color on hover state', 'rukhsar' ),
                'desc'        => esc_html__('Pick your color for hover state in hyperlink. Default color is black/grey #000000', 'rukhsar' ),
                'std'         => '',
                'type'        => 'colorpicker',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'heading_color',
                'label'       => esc_html__('Color on Heading', 'rukhsar' ),
                'desc'        => esc_html__('Pick your color for heading text. Default color is black #000000', 'rukhsar' ),
                'std'         => '',
                'type'        => 'colorpicker',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'general_color',
                'label'       => esc_html__('Color on General Paragraph', 'rukhsar' ),
                'desc'        => esc_html__('Pick your color for general paragraph text. Default color is black #7d7d7d', 'rukhsar' ),
                'std'         => '',
                'type'        => 'colorpicker',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),

            array(
                'id'          => 'footer_color',
                'label'       => esc_html__('Footer Background color', 'rukhsar' ),
                'desc'        => esc_html__('Pick your background color for footer. Default color is black #000000', 'rukhsar' ),
                'std'         => '',
                'type'        => 'colorpicker',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'color_menu',
                'label'       => esc_html__('Menu Background color', 'rukhsar' ),
                'desc'        => esc_html__('Pick your background color for menu. Default color is black #ffffff', 'rukhsar' ),
                'std'         => '',
                'type'        => 'colorpicker',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'stick_menu',
                'label'       => esc_html__('Sticky Menu Background color', 'rukhsar' ),
                'desc'        => esc_html__('Pick your background color for sticky menu. Default color is black #ffffff', 'rukhsar' ),
                'std'         => '',
                'type'        => 'colorpicker',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'custom_css_box',
                'label'       => esc_html__('Custom Css Box', 'rukhsar' ),
                'desc'        => esc_html__('Insert your own css/style code here.', 'rukhsar' ),
                'std'         => '',
                'type'        => 'css',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'logo_tab',
                'label'       => esc_html__('Logo', 'rukhsar' ),
                'desc'        => '',
                'std'         => '',
                'type'        => 'tab',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'logo_img',
                'label'       => esc_html__('Logo Upload', 'rukhsar' ),
                'desc'        => esc_html__('Upload your logo here.<br> Recommended size 185x60px', 'rukhsar' ),
                'std'         => '',
                'type'        => 'upload',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'logo_top_img',
                'label'       => esc_html__('Top Logo Upload', 'rukhsar' ),
                'desc'        => esc_html__('Upload your top logo here.<br> Recommended size 64x74px', 'rukhsar' ),
                'std'         => '',
                'type'        => 'upload',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),

            array(
                'id'          => 'favicon_logo',
                'label'       => esc_html__('Favicon Logo', 'rukhsar' ),
                'desc'        => esc_html__('Upload your favicon here. Recommended size 30x30px', 'rukhsar' ),
                'std'         => '',
                'type'        => 'upload',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'touch_logo',
                'label'       => esc_html__('Touch Logo', 'rukhsar' ),
                'desc'        => esc_html__('Upload your touch logo here. Recommended size 129x129px', 'rukhsar' ),
                'std'         => '',
                'type'        => 'upload',
                'section'     => 'general',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'slider_list',
                'label'       => esc_html__('Homepage Slider List', 'rukhsar' ),
                'desc'        => esc_html__('Create your slider list for main/homepage slider.<br/> For homepage with video/youtube background <b>the slider images will appear on touch devices</b> (replacing the video/youtube video).', 'rukhsar' ),
                'std'         => '',
                'type'        => 'list-item',
                'section'     => 'slider_sectio',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and',
                'settings'    => array(
                    array(
                        'id'          => 'slider_image',
                        'label'       => esc_html__('Slider Image', 'rukhsar' ),
                        'desc'        => esc_html__('Upload your slider image here. You can leave it blank if you are using homepage background video template.', 'rukhsar' ),
                        'std'         => '',
                        'type'        => 'upload',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'min_max_step'=> '',
                        'class'       => '',
                        'condition'   => '',
                        'operator'    => 'and'
                    ),
                    array(
                        'id'          => 'bottom_text',
                        'label'       => esc_html__('Slider bottom text', 'rukhsar' ),
                        'desc'        => esc_html__('Input your slider small text here.', 'rukhsar' ),
                        'std'         => '',
                        'type'        => 'textarea-simple',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'min_max_step'=> '',
                        'class'       => '',
                        'condition'   => '',
                        'operator'    => 'and'
                    ),
                    array(
                        'id'          => 'slider_link',
                        'label'       => esc_html__( 'Slider Link Button', 'rukhsar' ),
                        'desc'        => esc_html__( 'Input your slider button link here( leave it blank if you don\'t want it)', 'rukhsar' ),
                        'std'         => '',
                        'type'        => 'text',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'min_max_step'=> '',
                        'class'       => '',
                        'condition'   => '',
                        'operator'    => 'and'
                    ),
                    array(
                        'id'          => 'slider_link_text',
                        'label'       => esc_html__( 'Slider Link Text', 'rukhsar' ),
                        'desc'        => esc_html__( 'Input your slider text link here( leave it blank if you don\'t want it)', 'rukhsar' ),
                        'std'         => '',
                        'type'        => 'text',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'min_max_step'=> '',
                        'class'       => '',
                        'condition'   => '',
                        'operator'    => 'and'
                    )

                )
            ),
            array(
                'id'          => 'slider_delay',
                'label'       => esc_html__('Homepage Slider Delay', 'rukhsar' ),
                'desc'        => esc_html__('Set your slider delay here.', 'rukhsar' ),
                'std'         => '10000',
                'type'        => 'numeric-slider',
                'section'     => 'slider_sectio',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '1,10000,1',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),

            array(
                'id'          => 'fot_text_tab',
                'label'       => esc_html__('Footer Text', 'rukhsar' ),
                'std'         => '',
                'type'        => 'tab',
                'section'     => 'footer_section',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'fot_text',
                'label'       => esc_html__('Footer Text', 'rukhsar' ),
                'desc'        => esc_html__('Input footer text here. You can use HTML tag here.', 'rukhsar' ),
                'std'         => '',
                'type'        => 'textarea-simple',
                'rows'        => '3',
                'section'     => 'footer_section',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'fot_soc_tab',
                'label'       => esc_html__('Footer Social Icon', 'rukhsar' ),
                'std'         => '',
                'type'        => 'tab',
                'section'     => 'footer_section',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'fb_foot',
                'label'       => esc_html__('Facebook Link', 'rukhsar' ),
                'desc'        => esc_html__('Input facebook link here', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'footer_section',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'gp_foot',
                'label'       => esc_html__('Google Plus Link', 'rukhsar' ),
                'desc'        => esc_html__('Input google plus link here', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'footer_section',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'twit_foot',
                'label'       => esc_html__('Twitter Link', 'rukhsar' ),
                'desc'        => esc_html__('Input twitter link here', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'footer_section',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'pint_foot',
                'label'       => esc_html__('Pinterest Link', 'rukhsar' ),
                'desc'        => esc_html__('Input pinterest link here', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'footer_section',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'insta_link',
                'label'       => esc_html__('Instagram Link', 'rukhsar' ),
                'desc'        => esc_html__('Input instagram link here', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'footer_section',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'xing_foot',
                'label'       => esc_html__('Xing Link', 'rukhsar' ),
                'desc'        => esc_html__('Input xing link here', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'footer_section',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'foot_as_icon',
                'label'       => esc_html__('Another Social Icon', 'rukhsar' ),
                'desc'        => esc_html__('Create list for another social icon.', 'rukhsar' ),
                'std'         => '',
                'type'        => 'list-item',
                'section'     => 'footer_section',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and',
                'settings'    => array(
                    array(
                        'id'          => 'foot_soc_icon',
                        'label'       => esc_html__('Social Icon', 'rukhsar' ),
                        'desc'        => esc_html__('Input your social icon here. <br /> You can check <a target="_blank" href="http://fontawesome.io/icons/">Here</a> for icon list. eg. fa-github', 'rukhsar' ),
                        'std'         => '',
                        'type'        => 'text',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'min_max_step'=> '',
                        'class'       => '',
                        'condition'   => '',
                        'operator'    => 'and'
                    ),
                    array(
                        'id'          => 'foot_as_link',
                        'label'       => esc_html__('Social Icon Link', 'rukhsar' ),
                        'desc'        => esc_html__('Input social icon link here', 'rukhsar' ),
                        'std'         => '',
                        'type'        => 'text',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'min_max_step'=> '',
                        'class'       => '',
                        'condition'   => '',
                        'operator'    => 'and'
                    )
                )
            ),
            array(
                'id'          => 'custom_layout',
                'label'       => esc_html__('Section List','rukhsar'),
                'desc'        => esc_html__('Create your sections list here.<br/> Noted: <b>The title</b> on custom section will be the <b>id/anchor</b> to put in your homepage menu. <br/>
		Make sure <b>the title</b> doesn\'t have <b>space/white area</b> or <b>any special character</b>.','rukhsar'),
                'std'         => '',
                'type'        => 'list-item',
                'section'     => 'custom_layout_sec',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'settings'    => array(
                    array(
                        'id'          => 'section_type',
                        'label'       => esc_html__('Select Section','rukhsar'),
                        'desc'        => esc_html__('Select the section that you want to add in homepage','rukhsar'),
                        'std'         => '',
                        'type'        => 'select',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'min_max_step'=> '',
                        'class'       => '',
                        'choices'     => array(
                            array(
                                'value'       => 'about_content',
                                'label'       => esc_html__('About Section', 'rukhsar'),
                                'src'         => ''
                            ),
                            array(
                                'value'       => 'portfolio_content',
                                'label'       => esc_html__('Works Section', 'rukhsar'),
                                'src'         => ''
                            ),
                            array(
                                'value'       => 'services_content',
                                'label'       => esc_html__('Services Section', 'rukhsar'),
                                'src'         => ''
                            ),
                            array(
                                'value'       => 'contact_content',
                                'label'       => esc_html__('Contact Section', 'rukhsar'),
                                'src'         => ''
                            ),
                            array(
                                'value'       => 'custom_content',
                                'label'       => esc_html__('Custom Section', 'rukhsar'),
                                'src'         => ''
                            ),
                        ),
                    ),
                    array(
                        'id'          => 'custom_section',
                        'label'       => esc_html__('Custom Section', 'rukhsar' ),
                        'desc'        => esc_html__('Choose your custom section post here.', 'rukhsar' ),
                        'std'         => '',
                        'type'        => 'custom-post-type-select',
                        'section'     => 'custom_layout_sec',
                        'rows'        => '',
                        'post_type'   => 'custom-section',
                        'taxonomy'    => '',
                        'min_max_step'=> '',
                        'class'       => '',
                        'condition'   => 'section_type:is(custom_content)',
                        'operator'    => 'and'
                    ),
                )
            ),
            array(
                'id'          => 'section_block_title',
                'label'       => esc_html__('SECTION SETTINGS', 'rukhsar' ),
                'desc'        => esc_html__('You can set up each section in homepage here.', 'rukhsar' ),
                'std'         => '',
                'type'        => 'textblock-titled',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),

            array(
                'id'          => 'works_portfolio_setting_tab',
                'label'       => esc_html__('Works', 'rukhsar' ),
                'desc'        => '',
                'std'         => '',
                'type'        => 'tab',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'port_block',
                'label'       => esc_html__('You can create each portfolio item in portfolio post.', 'rukhsar' ),
                'desc'        => esc_html__('For creating new portfolio item, go to left menu Portfolio -> Add New Portfolio', 'rukhsar' ),
                'std'         => '',
                'type'        => 'textblock-titled',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'works_small_title',
                'label'       => esc_html__('Works Small Title', 'rukhsar' ),
                'desc'        => esc_html__('Insert your small title for works section here. eg. Portfolio / Project', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),

            array(
                'id'          => 'works_big_title',
                'label'       => esc_html__('Works Big Title', 'rukhsar' ),
                'desc'        => esc_html__('Insert your big title for works section here. eg. The Works', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'works_opening_text',
                'label'       => esc_html__('Works Detail Text', 'rukhsar' ),
                'desc'        => esc_html__('Insert your detail text for works section here', 'rukhsar' ),
                'std'         => '',
                'type'        => 'textarea-simple',
                'section'     => 'sections_setting',
                'rows'        => '3',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'works_all',
                'label'       => esc_html__('Works Filter for all categories', 'rukhsar' ),
                'desc'        => esc_html__('Insert your text for works filter for all categories. The default text is "All"', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '3',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),

            array(
                'id'          => 'about_section_tab',
                'label'       => esc_html__('About', 'rukhsar' ),
                'desc'        => '',
                'std'         => '',
                'type'        => 'tab',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'about_block',
                'label'       => esc_html__('You can create about post in About Us.', 'rukhsar' ),
                'desc'        => esc_html__('For creating about post, go to left menu About Us -> Add New About Us. <br>Only 1 about post will appear in homepage.', 'rukhsar' ),
                'std'         => '',
                'type'        => 'textblock-titled',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'about_small_title',
                'label'       => esc_html__('About Small Title', 'rukhsar' ),
                'desc'        => esc_html__('Insert your small title for about section here. eg. History / journey', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'about_big_title',
                'label'       => esc_html__('About Big Title', 'rukhsar' ),
                'desc'        => esc_html__('Insert your big title for about section here. eg. The Story', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'about_subtitle',
                'label'       => esc_html__('About Detail Text', 'rukhsar' ),
                'desc'        => esc_html__('Insert your detail text for about section here', 'rukhsar' ),
                'std'         => '',
                'type'        => 'textarea-simple',
                'section'     => 'sections_setting',
                'rows'        => '3',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'services_section_tab',
                'label'       => esc_html__('Services', 'rukhsar' ),
                'desc'        => '',
                'std'         => '',
                'type'        => 'tab',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'services_block',
                'label'       => esc_html__('You can create services list in services post.', 'rukhsar' ),
                'desc'        => esc_html__('For creating new services list, go to left menu Services Posts -> Add New Services Post', 'rukhsar' ),
                'std'         => '',
                'type'        => 'textblock-titled',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'services_open_text',
                'label'       => esc_html__('Services Small Title', 'rukhsar' ),
                'desc'        => esc_html__('Insert your small title for services section here.', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '3',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'services_big_title',
                'label'       => esc_html__('Services Big Title', 'rukhsar' ),
                'desc'        => esc_html__('Insert your big title for services section here. eg. The Expertise', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'services_sub_text',
                'label'       => esc_html__('Services Detail Text', 'rukhsar' ),
                'desc'        => esc_html__('Insert your detail text for services section here.', 'rukhsar' ),
                'std'         => '',
                'type'        => 'textarea-simple',
                'section'     => 'sections_setting',
                'rows'        => '3',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'services_list',
                'label'       => esc_html__('Services Slider', 'rukhsar' ),
                'desc'        => esc_html__('Create your services slider  here.', 'rukhsar' ),
                'std'         => '',
                'type'        => 'list-item',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and',
                'settings'    => array(
                    array(
                        'id'          => 'sliderservice_image',
                        'label'       => esc_html__('Slider Image', 'rukhsar' ),
                        'desc'        => esc_html__('Upload your slider images here.', 'rukhsar' ),
                        'std'         => '',
                        'type'        => 'upload',
                        'rows'        => '',
                        'post_type'   => '',
                        'taxonomy'    => '',
                        'min_max_step'=> '',
                        'class'       => '',
                        'condition'   => '',
                        'operator'    => 'and'
                    )
                )
            ),
            array(
                'id'          => 'contact_section_tab',
                'label'       => __( 'Contact', 'rukhsar' ),
                'desc'        => '',
                'std'         => '',
                'type'        => 'tab',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'contact_block',
                'label'       => __( 'You can create contact post in contact post.', 'rukhsar' ),
                'desc'        => __( 'For creating contact post or inserting contact form 7 shortcode, go to left menu Contact Posts -> Add New Contact Post', 'rukhsar' ),
                'std'         => '',
                'type'        => 'textblock-titled',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'contact_small_title',
                'label'       => __( 'Contact Small Title', 'rukhsar' ),
                'desc'        => __( 'Insert your small title for contact section here.', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'contact_big_title',
                'label'       => __( 'Contact Big Title', 'rukhsar' ),
                'desc'        => __( 'Insert your big title for contact section here. eg. The Contact', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'contact_sub_title',
                'label'       => __( 'Contact Detail Text', 'rukhsar' ),
                'desc'        => __( 'Insert your detail text for contact section here. eg. The Contact', 'rukhsar' ),
                'std'         => '',
                'type'        => 'textarea-simple',
                'section'     => 'sections_setting',
                'rows'        => '3',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),


            array(
                'id'          => 'tx_address',
                'label'       => __( 'Insert Text for Address', 'rukhsar' ),
                'desc'        => __( 'Insert text for address here. The default text is Address', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),

            array(
                'id'          => 'map_address',
                'label'       => __( 'Address', 'rukhsar' ),
                'desc'        => __( 'Insert your address here. <br/>Leave it blank if you don\'t need it', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),

            array(
                'id'          => 'tx_phone',
                'label'       => __( 'Insert Text for Phone', 'rukhsar' ),
                'desc'        => __( 'Insert text for phone here. The default text is Phone', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'map_phone',
                'label'       => __( 'Phone', 'rukhsar' ),
                'desc'        => __( 'Insert your phone here. <br/>Leave it blank if you don\'t need it', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
            array(
                'id'          => 'tx_email',
                'label'       => __( 'Insert Text for Email', 'rukhsar' ),
                'desc'        => __( 'Insert text for email here. The default text is Email', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),

            array(
                'id'          => 'map_email',
                'label'       => __( 'Email', 'rukhsar' ),
                'desc'        => __( 'Insert your email here. <br/>Leave it blank if you don\'t need it', 'rukhsar' ),
                'std'         => '',
                'type'        => 'text',
                'section'     => 'sections_setting',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'min_max_step'=> '',
                'class'       => '',
                'condition'   => '',
                'operator'    => 'and'
            ),
        )
    );

    /* allow settings to be filtered before saving */
    $custom_settings = apply_filters( ot_settings_id() . '_args', $custom_settings );

    /* settings are not the same update the DB */
    if ( $saved_settings !== $custom_settings ) {
        update_option( ot_settings_id(), $custom_settings );
    }

    /* Lets OptionTree know the UI Builder is being overridden */
    global $ot_has_custom_theme_options;
    $ot_has_custom_theme_options = true;
}